# Generated by Django 5.0 on 2023-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_weight',
            field=models.IntegerField(default=1, help_text='Вес вопроса'),
        ),
    ]
