# Generated by Django 5.0 on 2023-12-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_question_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type_of_questions',
            field=models.CharField(choices=[('single', 'единственный выбор'), ('multiple', 'множественный выбор'), ('range', 'ранжирование'), ('mapping', 'сопоставление')], default='единственный выбор', max_length=25),
        ),
    ]
