# Generated by Django 5.0 on 2023-12-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_question_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('единственный выбор', 'единственный выбор'), ('множественный выбор', 'множественный выбор'), ('ранжирование', 'ранжирование')], default='единственный выбор', max_length=254),
        ),
    ]
